name: CI

on:
  - push

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: php-actions/composer@v5
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          REDIS_HOST: redis
          REDIS_PORT: "6379"
          REDIS_PASSWORD: ""
        with:
          bootstrap: vendor/autoload.php
#          configuration: test/phpunit.xml
          args: tests/ --coverage-text
